### ISSUE TITLE
Document the `limit` option

### ISSUE THREAD

**Issue by feross** [Zertz/mollusc#28]
👋 Hey, great module!

I want to use the `limit` option which I found in the source here:

https://github.com/Zertz/mollusc/blob/a18326b75932d94a84c80eed5dde4143e148a3aa/slug.js#L98-L102

but it's unclear if it will be supported long-term or it is meant to be used publicly. Is it a public API?

**Comment by Zertz** [comment]
Yes! I must have forgot about it when I wrote the docs but it's [tested](https://github.com/Zertz/mollusc/blob/master/test.js#L283) and meant to be used.

Thank you!
